---

- name: Collect kernel name
  shell: uname -s
  register: s

- name: Collect machine hardware name
  shell: uname -m
  register: m

- name: Download docker-compose binary
  uri:
    url: "https://github.com/docker/compose/releases/download/{{ dc_ver }}/docker-compose-{{ s.stdout }}-{{ m.stdout }}"
    method: GET
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: "0755"
    force: yes
  become: yes

- name: Download Command-line completion
  uri:
    url: "https://raw.githubusercontent.com/docker/compose/{{ dc_ver }}/contrib/completion/bash/docker-compose"
    method: GET
    dest: /etc/bash_completion.d/docker-compose
    owner: root
    group: root
    mode: "0644"
    force: yes
  become: yes

- name: Try run docker-compose
  shell: docker-compose --version
