---

- name: Collect some facts
  set_fact:
    kernel: "{{ ansible_facts['system'] }}"
    machine: "{{ ansible_facts['machine'] }}"

- name: Download docker-compose binary
  uri:
    url: "https://github.com/docker/compose/releases/download/{{ dc_ver }}/docker-compose-{{ kernel }}-{{ machine }}"
    method: GET
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: "0755"
    force: yes
    status_code:
      - "200"
      - "304"
  become: yes

- name: Download Command-line completion
  uri:
    url: "https://raw.githubusercontent.com/docker/compose/{{ dc_ver }}/contrib/completion/bash/docker-compose"
    method: GET
    dest: /etc/bash_completion.d/docker-compose
    owner: root
    group: root
    mode: "0644"
    force: yes
    status_code:
      - "200"
      - "304"
  become: yes

# @see https://docs.ansible.com/ansible/latest/scenario_guides/guide_docker.html
- name: Install python3-pip
  apt:
    pkg:
      - python3-pip
    state: latest
    update_cache: yes
  become: yes

- name: Install docker-compose for Python
  pip:
    name: docker-compose
    state: latest
