---

- name: Collect some facts
  set_fact:
    kernel: "{{ ansible_facts['system'] }}"
    machine: "{{ ansible_facts['machine'] }}"

- name: Download docker-compose binary
  uri:
    url: "https://github.com/docker/compose/releases/download/{{ dc_ver }}/docker-compose-{{ kernel }}-{{ machine }}"
    method: GET
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: "0755"
    force: yes
  become: yes

- name: Download Command-line completion
  uri:
    url: "https://raw.githubusercontent.com/docker/compose/{{ dc_ver }}/contrib/completion/bash/docker-compose"
    method: GET
    dest: /etc/bash_completion.d/docker-compose
    owner: root
    group: root
    mode: "0644"
    force: yes
    status_code:
      - "200"
      - "304"
  become: yes

- name: Try run docker-compose
  shell: docker-compose --version
  register: docker_compose_version
  changed_when: docker_compose_version.failed

- name: Print output
  debug:
    msg: "{{ docker_compose_version.stdout }}"
